package remote.corba;


/**
* remote/corba/BankServerRemoteOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from BankServer.idl
* Sunday, October 22, 2017 6:52:51 PM EDT
*/

public interface BankServerRemoteOperations 
{
  String transferAccount (String firstName, String lastName, String address, String phone, String balance);
  String createAccountRecord (String managerId, String firstName, String lastName, String address, String phone, String branch);
  String editRecord (String managerId, String customerId, String fieldName, String newValue);
  String deposit (String customerId, String amount);
  String withdraw (String customerId, String amount);
  String getBalance (String customerId);
  void shutdown ();
} // interface BankServerRemoteOperations
