package remote.corba;


/**
* remote/corba/BankServerRemote.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from BankServer.idl
* Sunday, October 22, 2017 6:52:51 PM EDT
*/

public interface BankServerRemote extends BankServerRemoteOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface BankServerRemote
