package fe._FEPackage;


/**
* _FEPackage/FrontEndOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from FrontEnd.idl
* Friday, November 24, 2017 11:04:17 o'clock AM EST
*/

public interface FrontEndOperations 
{
  String deposit (String customerID, int amount);
  String withdraw (String customerID, int amount);
  int getBalance (String customerID);
  String transferFund (String sourceCustomerID, int amount, String destinationCustomerID);
  String createAccountRecord (String managerID, String firstName, String lastName, String address, String phone, String branch);
  String editRecord (String managerID, String customerID, String fieldName, String newValue);
  String getAccountCount (String managerID);
  String transferFundManager (String managerID, int amount, String sourceCustomerID, String destinationCustomerID);
  void shutdown ();
} // interface FrontEndOperations
