package fe._FEPackage;

/**
* fe._FEPackage/FrontEndHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from FrontEnd.idl
* Friday, November 24, 2017 11:04:17 o'clock AM EST
*/

public final class FrontEndHolder implements org.omg.CORBA.portable.Streamable
{
  public fe._FEPackage.FrontEnd value = null;

  public FrontEndHolder ()
  {
  }

  public FrontEndHolder (fe._FEPackage.FrontEnd initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = fe._FEPackage.FrontEndHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    fe._FEPackage.FrontEndHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return fe._FEPackage.FrontEndHelper.type ();
  }

}
