package fe.corba;

/**
* fe.corba/FrontEndHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from FrontEnd.idl
* Tuesday, November 28, 2017 2:55:11 o'clock PM EST
*/

public final class FrontEndHolder implements org.omg.CORBA.portable.Streamable
{
  public fe.corba.FrontEnd value = null;

  public FrontEndHolder ()
  {
  }

  public FrontEndHolder (fe.corba.FrontEnd initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = fe.corba.FrontEndHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    fe.corba.FrontEndHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return fe.corba.FrontEndHelper.type ();
  }

}
