package fe.corba;


/**
* _FEPackage/FrontEnd.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from FrontEnd.idl
* Friday, November 24, 2017 11:04:17 o'clock AM EST
*/

public interface FrontEnd extends FrontEndOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity
{
} // interface FrontEnd
