package fe.corba;


/**
* _FEPackage/FrontEndOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from FrontEnd.idl
* Tuesday, November 28, 2017 2:55:11 o'clock PM EST
*/

public interface FrontEndOperations 
{
  String deposit (String customerID, String amount);
  String withdraw (String customerID, String amount);
  String getBalance (String customerID);
  String transferFund (String sourceCustomerID, String amount, String destinationCustomerID);
  String createAccountRecord (String managerID, String firstName, String lastName, String address, String phone, String branch);
  String editRecord (String managerID, String customerID, String fieldName, String newValue);
  String getAccountCount (String managerID);
  String transferFundManager (String managerID, String amount, String sourceCustomerID, String destinationCustomerID);
  void shutdown ();
} // interface FrontEndOperations
